### ISSUE TITLE
Announcement API

### ISSUE THREAD

**Issue by elct9620** [CCIP-App/CCIP-Serverless#5]
讓 CCIP Serverless 支援 Announcement API

### Ref
- Current impl: https://github.com/CCIP-App/CCIP-Server/blob/5175429a0418fde9cfe636ee1107001a17343215/app/ccip.py#L291-L315
- UI (Android) schema: https://github.com/CCIP-App/CCIP-Android/blob/dev/app/src/main/java/app/opass/ccip/model/Announcement.kt

---
## Story 1

User could query a list of announcements via GET /announcement without a token

### Todos

- [x] Core: Add announcement domain entity #17
- [x] API: Add repo #17
- [x] API: Add usecase #18
- [x] E2E test: Add scenario #20
- [x] Worker: Add endpoint #22

## Story 2

User could create a an announcements via POST /announcement

- #27 
- #28 
- #35
- #36

**Comment by dannyh79** [comment]
@elct9620 

_Context: 看起來 announcements 和 roles 是多對多的關係（另外，一個 attendee 只能是一種 role ）。_

關於[同一筆 announcement 要可以被不同的 role 存取的需求](https://github.com/CCIP-App/CCIP-Server/blob/master/app/ccip.py#L304)，於 serverless D1 DB 的實作目前有想到以下兩個方案：

1. 創立 announcements_roles 表，內有 FK 欄位 `announcements_id` 和字串欄位 `role` （值由 app 定義，如 `"audience"` 或是 `"staff"` ）
    - 優：不會動到 attendees 表
2. 創立 announcements_roles ， roles 和調整 attendees.role 表，讓其為 `roles_id`
    - 優：正規化
    - 缺：整個 project 於 prod 或 test 環境初始化時可能需要有 task 來先加入 default role data

若沒有其他考量的話，稍後預計採用方案 1 。

**Comment by dannyh79** [comment]
Completed by 1152107. Closing.
